-- AlterTable
ALTER TABLE "User" ALTER COLUMN "costPerCigg" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "initDailyAvg" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "duration" SET DATA TYPE DOUBLE PRECISION;
